"""empty message

Revision ID: e74d54afa5db
Revises: 180e4cbd02c3
Create Date: 2022-02-15 08:52:51.936111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74d54afa5db'
down_revision = '180e4cbd02c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_image')
    # ### end Alembic commands ###
