"""empty message

Revision ID: 3cd57bad6016
Revises: d3b3b80a69ea
Create Date: 2022-02-26 09:14:51.370270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd57bad6016'
down_revision = 'd3b3b80a69ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'room_id')
    # ### end Alembic commands ###
