"""empty message

Revision ID: 4ccb12a76174
Revises: 59e7fbf3b056
Create Date: 2022-03-20 10:41:09.546942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccb12a76174'
down_revision = '59e7fbf3b056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
