"""empty message

Revision ID: 29054ba7cf42
Revises: e7c7fbefafa9
Create Date: 2022-02-19 11:27:45.890221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29054ba7cf42'
down_revision = 'e7c7fbefafa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendee',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendee')
    op.drop_table('events')
    # ### end Alembic commands ###
