"""empty message

Revision ID: d7801d385a87
Revises: 
Create Date: 2022-02-15 12:52:29.282071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7801d385a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_room_name_key', 'rooms', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rooms_room_name_key', 'rooms', ['room_name'])
    # ### end Alembic commands ###
