"""empty message

Revision ID: ccbf77fac8a5
Revises: d7801d385a87
Create Date: 2022-02-15 20:05:37.288223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbf77fac8a5'
down_revision = 'd7801d385a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'note_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'note_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
